### PR TITLE
Move from velocity:1.7 to velocity-engine-core:2.3

### LINKED ISSUE #578: Hollow depends on org.apache.velocity:velocity:1.7
The dependency on org.apache.velocity:velocity:1.7 introduces vulnerability to https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHEVELOCITY-3116414, ranked as a High impact.

### PR DESCRIPTION
**Pull request by rydenius**
A simplistic attempt to resolve https://github.com/Netflix/hollow/issues/578 security issue. I have just checked that the build passes, no manual testing done on my side.

### CODE REVIEW

**Comment by mailsanchu** [comment]
Can you please ask in gitter to review this code
https://gitter.im/Netflix/hollow

**Comment by rydenius** [comment]
Thanks. I just posted about it on Gitter now.

**Comment by Sunjeet** [comment]
Incorporated in https://github.com/Netflix/hollow/pull/584 . I bundled it together in that PR and tested everything together, seems good.

**Comment by Sunjeet** [comment]
Thank you!

**Comment by rydenius** [comment]
Great! 👍

**Pull request closed without merging**
