### PR TITLE
Metrics and metrics collector

### PR DESCRIPTION
**Pull request by rpalcolea**
This is for https://github.com/Netflix/hollow/issues/76

This is only the first phase which contains the implementation for the core metrics.

The external module would be implemented in a 2nd phase

### CODE REVIEW

**Comment by kineshsatiya** [comment]
Quick question, any particular reason, `HollowProducerListener` and `HollowUpdateListener` are not being used to collect metrics. We could have default implementations and people could hook them up when creating producers and consumers.

**Comment by rpalcolea** [comment]
That is a great question @kineshsatiya 

When I thought about this, my first idea was to create it independent of the listeners. I didn't know if it would be a good idea to have a default listener and allow users to add their own ones.. or provide a base implementation and let them override it as needed. That's why I created it as a separate thing that always happens, because more likely, everyone would like to have metrics around the consumers and/or producer. 

That was the main driver to go into this direction where metrics are collected always no matter if you add or not listeners. 

Is there a preference for this? I could definitely refactor based on what you think is better for this use case. Also, if you have more feedback around the metrics itself and the collector interface would be great.

**Comment by rpalcolea** [comment]
ready for review @dkoszewnik

**Review by dkoszewnik — APPROVED** [review]

**Comment by rpalcolea** [comment]
Updated to use the changes in https://github.com/Netflix/hollow/pull/104

**Comment by kineshsatiya** [comment]
@rpalcolea So the reason I was inclined to use listeners for recording metrics, is so that the code in `HollowProducer` for making the right callbacks at completion of each stage could be reused. 

However, I do not strongly feel about using metrics as listeners, since by default collecting those metrics might be a good idea, compared to providing a choice. So going ahead and merging this change.

**Comment by costimuraru** [comment]
@rpalcolea nice job on adding the metrics.

I'm getting an error though on:
`HollowProducerMetrics.java:48`
```java
HollowReadStateEngine hollowReadStateEngine = producerStatus.getReadState().getStateEngine();
```
It seems the `producerStatus.getReadState()` is null.

```java
java.lang.NullPointerException
	at com.netflix.hollow.api.metrics.HollowProducerMetrics.updateCycleMetrics(HollowProducerMetrics.java:48)
	at com.netflix.hollow.api.producer.HollowProducer.runCycle(HollowProducer.java:299)
	at com.netflix.hollow.api.producer.HollowProducer.runCycle(HollowProducer.java:299)
```

**Comment by rpalcolea** [comment]
Mm interesting, I wouldn’t expect the read state to be null.

I’ll open a pr soon to check for this.

Any details you could share on this? And specific state?

Thanks

**Comment by rpalcolea** [comment]
Opened a PR to fix this @costimuraru  -> https://github.com/Netflix/hollow/pull/110

**Comment by costimuraru** [comment]
Thanks for quick response, @rpalcolea!
I'm a bit puzzled myself onto why the state is null (it happens when I run the first runCycle on the producer) - I'll have to dig in.

hollow

**Comment by rpalcolea** [comment]
@costimuraru 

Yeah, looks like it is a valid scenario https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducerListener.java#L209

Totally omitted that possibility. Hopefully the fix will be merged and released soon!

My bad 😔

**Comment by costimuraru** [comment]
Cool, mystery solved :D
Thanks! Keep up the great work.

**Pull request merged**
