### PR TITLE
Bug fix for deleted records being inserted into the write state as Object

### PR DESCRIPTION
**Pull request by duro1**
This caused a restore operation to fail with "java.lang.IllegalStateException: When state engine was restored, not all necessary states were present!  Unrestored states: [Object]"

Used static DELETE_RECORD object from HollowIncrementalCyclePopulator when adding items to be deleted to the mutations collection
Removed misleading DELETE_RECORD from HollowIncrementalProducer

### CODE REVIEW

**Comment by duro1** [comment]
@toolbear Please take a look at this bugfix for an issue that was introduced with release v2.9.9

FYI: @rpalcolea @tinetti

**Review by rpalcolea — APPROVED** [review]
LGTM

**Comment by duro1** [comment]
@toolbear @dkoszewnik @akhaku Can I get a merge?

**Comment by akhaku** [comment]
Thanks!

**Comment by duro1** [comment]
@akhaku Thanks for the PR!  Do you think these changes could be included in a patch release soon?

**Comment by akhaku** [comment]
Absolutely - planning on doing a release of this and #189 some time today.

**Pull request merged**
